package com.garageos.core.enums;

public enum JobCardStatus {

    OPEN,
    INSPECTION_PENDING,
    INSPECTION_COMPLETED,
    ESTIMATE_PENDING,
    WAITING_FOR_APPROVAL,
    REPAIR_IN_PROGRESS,
    QUALITY_CHECK,
    READY_FOR_DELIVERY,
    DELIVERED,
    CANCELLED,
    ESTIMATE_APPROVED,
    REPAIR_PENDING,
    REPAIR_COMPLETED,
    INVOICE_GENERATED,
    READY_FOR_INVOICE,
    INVOICED,
    PAYMENT_PENDING,
    PAYMENT_COMPLETED,
    WORK_COMPLETED,
    CLOSED

}