spring.application.name=garageos-backend

spring.datasource.url=jdbc:postgresql://localhost:5432/garageos
spring.datasource.username=postgres
spring.datasource.password=varun@98

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

server.port=8080