ALTER TABLE garage
ADD COLUMN next_employee_sequence INTEGER NOT NULL DEFAULT 1;

-- Backfill: for garages that already have employee codes generated by the
-- previous MAX(existing code) + 1 logic, the counter must resume after the
-- highest existing sequence, not restart at 1 (which would immediately
-- collide with an existing employee_code and violate the new unique
-- constraint below).
UPDATE garage g
SET next_employee_sequence = COALESCE(
    (
        SELECT MAX(
            CAST(
                SUBSTRING(gm.employee_code FROM LENGTH(g.garage_code) + 5)
                AS INTEGER
            )
        ) + 1
        FROM garage_membership gm
        WHERE gm.garage_id = g.id
          AND gm.employee_code IS NOT NULL
          AND gm.employee_code LIKE g.garage_code || '-EMP%'
    ),
    1
)
WHERE g.garage_code IS NOT NULL;

ALTER TABLE garage_membership
ADD CONSTRAINT uq_garage_membership_employee_code UNIQUE (employee_code);
